# .Rprofile
# Auto-generated by Lipidomic Explorer Setup
# Establishes library path isolation on R session startup

local({
  sys_os <- Sys.info()["sysname"]
  r_ver <- paste0(R.version$major, ".", strsplit(R.version$minor, "\\.")[[1]][1])
  
  if (Sys.getenv("TEST_LIB_PATH") != "") {
    lib_path <- Sys.getenv("TEST_LIB_PATH")
  } else {
    if (sys_os == "Windows") {
      lib_path <- file.path(Sys.getenv("LOCALAPPDATA"), "LipidomicExplorer_R_Library", r_ver)
    } else if (sys_os == "Darwin") {
      arch <- Sys.info()["machine"]
      lib_path <- file.path(Sys.getenv("HOME"), "Library", "R", "LipidomicExplorer_Library", paste0(r_ver, "_", arch))
    } else {
      lib_path <- file.path(Sys.getenv("HOME"), ".R", "LipidomicExplorer_Library", r_ver)
    }
  }
  
  if (!dir.exists(lib_path)) {
    dir.create(lib_path, recursive = TRUE, showWarnings = FALSE)
  }
  
  .libPaths(c(lib_path, .Library))
  Sys.setenv(R_LIBS_USER = lib_path)
  message(paste("[LIPIDOMIC EXPLORER] Sandbox library path configured at:", lib_path))
})
